---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lab
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3

addons:
- name: vpc-cni # no version is specified so it deploys the default version
- name: coredns
  version: latest # auto discovers the latest available
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-dr